### ISSUE TITLE
Showing network is possible? 

### ISSUE THREAD

**Issue by gokhanko** [VincenzoPiromalli/moviewp#1]
Hi, thanks for this great theme. I am curious that is it possible to show networks on the left menu or single movie pages. Actually I want to create lists/collections.

**Comment by VincenzoPiromalli** [comment]
> Hi, thanks for this great theme. I am curious that is it possible to show networks on the left menu or single movie pages. Actually I want to create lists/collections.

Yes, it's possible :)
