### ISSUE TITLE
Tv servers - A suggestion

### ISSUE THREAD

**Issue by solomonshalom** [VincenzoPiromalli/moviewp#4]
Hey Vincenzo,

Your new update is amazing - I would really love it if you could add some more servers to tv series as well. Below are some servers that if you add, could be really great -

1. [Fsapi.xyz](https://fsapi.xyz/#embed-anime)
It gets movies, TV series & anime stream links by IMDB or TMDb ID. 

2. Stremio
This was really amazing in the movie section, would be great if you could add it to the tv series section

3. Curtstream
Ad less, amazing UI - add this to the tv, people will really like it

4. [Ani API](https://aniapi.com)
This is a really cool api to stream anime, they currently have a js wrapper. Maybe you could use it as well

These features would be really cool if you add them, thanks for the great theme :)

**Comment by VincenzoPiromalli** [comment]
> Hey Vincenzo,
> 
> Your new update is amazing - I would really love it if you could add some more servers to tv series as well. Below are some servers that if you add, could be really great -
> 
> 1. [Fsapi.xyz](https://fsapi.xyz/#embed-anime)
>    It gets movies, TV series & anime stream links by IMDB or TMDb ID.
> 2. Stremio
>    This was really amazing in the movie section, would be great if you could add it to the tv series section
> 3. Curtstream
>    Ad less, amazing UI - add this to the tv, people will really like it
> 4. [Ani API](https://aniapi.com)
>    This is a really cool api to stream anime, they currently have a js wrapper. Maybe you could use it as well
> 
> These features would be really cool if you add them, thanks for the great theme :)

**Fsapi.xyz**

i dont like it 👎 

**Stremio**

thanks,  :
for tv series use this type of link `https://vidcloud.stream/series/tt10919420/1/1.html` where /1/1 stands for /season/episode

**Curtstream**

already added a few days ago, maybe you didn't notice it (also it's full of advertisements)

**Ani API**

It does not support IMDB and TMDb
These features would be really cool if you add them, thanks for the great theme :)



Please note that the custom changes, custom works requests is only valid for those who buy the original product from the store, the same applies to support and monthly updates.

**Comment by solomonshalom** [comment]
Hey Vincenzo,

I didn't know that you added curtstream and stremio because I couldn't see them. I will try to re-install the update. One more thing - if possible, could you crawl links from animixplay? they have a lot of servers on their website. Thanks :)

**Comment by VincenzoPiromalli** [comment]
> Hey Vincenzo,
> 
> I didn't know that you added curtstream and stremio because I couldn't see them. I will try to re-install the update. One more thing - if possible, could you crawl links from animixplay? they have a lot of servers on their website. Thanks :)

Hello, I already answered you, the theme only and exclusively supports TMDB or IMDB ids, it does not support any other API concerning ANIME.
