### ISSUE TITLE
Suggestions/Bugs 

### ISSUE THREAD

**Issue by solomonshalom** [VincenzoPiromalli/moviewp#6]
Hey Vincenzo,

The new update you pushed is great, I wanted to know if there are sources that won't give a "We can't find the file you are looking for. It maybe got deleted by the owner or was removed due to a copyright violation". A source that would be able to find the anime or series/movie. One example could be animixplay or anime-kisa.xyz, a site that streams anime that has sources that work, that would be a great fix, I also want to know if you could add more social networks to the social section in the dashboard like GitHub or discord. Thank You

**Comment by VincenzoPiromalli** [comment]
Could you please stop making impossible requests plus assigning them to bugs? Thanks!

**Comment by VincenzoPiromalli** [comment]
There is no support and no updates for free version
