### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by solomonshalom** [VincenzoPiromalli/moviewp#7]
Hey Vincenzo,

Below are some suggestions that I would love to see in future updates -

1. Add a stream that won't give a "We can't find the file you are looking for. It maybe got deleted by the owner or was removed due to a copyright violation." If you can make a stream yourself that takes content from other websites like Fmovies, AniMixPlay or 123Movies then the issue is actually solved.

2.  Add more social network sections in the social section, for example - discord or GitHub

3. Add a custom field for advertisement, for example, a section that allows users to add iframe code to display advertisement. 

One more thing - these are suggestions, not requests. I just would love to see these in the upcoming updates. Thank You for the great theme :)

**Comment by VincenzoPiromalli** [comment]
There is no support and no updates for free version.
